#
# Blog Settings
#
author: Henrik Andersson
description: A former chef turned software developer specialising in .NET Framework stack, a father and husband with a beautiful wife and three wonderful children, a viking and originally from Sweden...no, not Switzerland.
url: http://henrikandersson.org
title: henrik andersson
subtitle: 
gravatar_url: https://s.gravatar.com/avatar/de0ee1937ada29a8c7be1db1505c690b
subscribe_rss: http://feeds.henrikandersson.org/ahandersson
display_resume: false

# Github repositories
github_user: alfhenrik
github_repo_url: https://github.com/alfhenrik/henrikandersson.org/

# Twitter
twitter_user: ahandersson
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: henrikandersson
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-37423173-1


#
# Jekyll Settings
#
markdown: rdiscount
pygments: true
permalink: /archive/:year/:month/:day/:title/
rdiscount:
  extensions: [smart]
paginate: 5
paginate_path: "page/:num"
category_dir: categories
excerpt_separator: "<!--break-->"
